pre-commit:
  parallel: true
  commands:
    black:
      run: black models/ notebooks/
    ruff:
      run: ruff check models/ notebooks/ --fix
    mypy:
      run: mypy models/
    nbstripout:
      run: nbstripout notebooks/**/*.ipynb || true