pre-commit:
  parallel: true
  commands:
    black:
      run: black dev/ models/ notebooks/
    ruff:
      run: ruff check dev/ models/ notebooks/ --fix
    mypy:
      run: mypy models/ dev/
    nbstripout:
      run: nbstripout notebooks/*.ipynb || true